[package]
name = "pixelsortery"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2.1.0"
eframe = "0.28.1"
egui_extras = "0.28.1"
env_logger = "0.11.5"
image = "0.24.6"
log = "0.4.22"
rand = "0.8.5"
rayon = "1.10.0"
rfd = "0.14.1"
