[package]
name = "pixelsortery"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2.1.0"
image = "0.24.6"
log = "0.4.22"
rand = "0.8.5"
stderrlog = "0.6.0"
