[package]
name = "pixelsortery_app"
authors = ["Lxtharia"]
version = "0.9.0"
edition = "2021"

[lib]
name = "pixelsortery"
path = "src/lib.rs"
crate-type = ["cdylib"]      # Creates dynamic lib
# crate-type = ["staticlib"] # Creates static lib

# [[bin]]
# name = "pixelsortery_bin"
# path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2.1.0"
eframe = "0.29.1"
egui = "0.29.1"
egui_extras = { version = "0.29.1", features = ["file", "image"] }
egui_flex = "0.1.1"
env_logger = "0.11.5"
image = { version = "0.24.6", features = ["jpeg", "png", "webp"] }
inflections = "1.1.1"
log = "0.4.22"
rand = "0.8.5"
rayon = "1.10.0"
rfd = "0.14.1"
